from .nodes.step_label import (
    NODE_CLASS_MAPPINGS as STEP_LABEL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STEP_LABEL_NODE_DISPLAY_NAME_MAPPINGS,
)

from .nodes.poster import (
    NODE_CLASS_MAPPINGS as POSTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POSTER_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **STEP_LABEL_NODE_CLASS_MAPPINGS,
    **POSTER_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **STEP_LABEL_NODE_DISPLAY_NAME_MAPPINGS,
    **POSTER_NODE_DISPLAY_NAME_MAPPINGS,
}


WEB_DIRECTORY = "web/js"


__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]